# Generated by Django 6.0.5 on 2026-05-26 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_bg_color', models.CharField(default='#338A85', max_length=7)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('language', models.CharField(default='English(US)', max_length=50)),
                ('region', models.CharField(default='Philippines (English)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
