# Generated by Django 6.0.5 on 2026-06-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pendingregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='English (US)', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(default='Philippines (GMT+8)', max_length=30),
        ),
    ]
